- name: set the stable docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install dependencies
  become: true
  become_method: sudo
  apt: pkg={{ item }} state=present 
  with_items:
      # GUI
      - ubuntu-desktop

      # VirtualBox
      - virtualbox-guest-utils
      - virtualbox-guest-dkms

      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv
      - python-pip
      - cmake

      # Git
      - git

      # Vim with clipboard support
      - vim-gtk

      # Docker
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

# - name: Debian add docker key
#   apt_key:
#     url: https://download.docker.com/linux/debian/gpg
#     state: present
#   become: true
#   when: "ansible_distribution == 'Debian'"

- name: Ubuntu add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    state: present
  become: true

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install packages
  become: true
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      # Docker
      - docker-ce

- name: Add vagrant to docker user
  command: usermod -a -G docker vagrant

- name: start docker container (busybox)
  docker_container:
    name: mydata
    image: busybox
    volumes:
      - /data

- name: install pycharm-professional via snap
  command: snap install pycharm-professional --classic --edge

- name: install intellij-idea-ultimate via snap
  command: snap install intellij-idea-ultimate --classic

- name: set timezone to America/Denver
  timezone:
    name: America/Denver


