- name: Install packages
  become: true
  become_method: sudo
  apt: pkg={{ item }} state=present 
  with_items:
      # GUI
      - ubuntu-desktop

      # Database
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # Required for Ansible to interact with postgres

      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv
      - python-pip
      - cmake

      # Git
      - git

      # Docker
      - docker.io

- name: install docker-py
  pip:
    name: docker-py

- name: ensure docker is running
  systemd: 
    name: docker
    state: started
    enabled: yes

- name: Add vagrant to docker user
  command: usermod -a -G docker vagrant

- name: start docker container (busybox)
  docker_container:
    name: mydata
    image: busybox
    volumes:
      - /data

- name: install pycharm-professional via snap
  command: snap install pycharm-professional --classic --edge

- name: install intellij-idea-ultimate via snap
  command: snap install intellij-idea-ultimate --classic
