- name: Install packages
  become: true
  become_method: sudo
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      # Database
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # Required for Ansible to interact with postgres

      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv
      - python-pip
      - cmake

      # Git
      - git

- name: ensure repository key is installed
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: ensure docker registry is available
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: ensure docker and dependencies are installed
  apt: name=docker-engine update_cache=yes

- service: name=docker state=restarted

- name: Uninstall python docker
  become: true
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-py
    - docker

- name: Install python docker
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker

- name: Add vagrant to docker user
  command: usermod -a -G docker vagrant

- name: start docker container (busybox)
  docker_container:
    name: mydata
    image: busybox
    volumes:
      - /data

- name: install pycharm-professional via snap
  command: snap install pycharm-professional --classic --edge


- name: install intellij-idea-ultimate via snap
  command: snap install intellij-idea-ultimate --classic
